// <auto-generated />
namespace ElasticaClients.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _46 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_46));
        
        string IMigrationMetadata.Id
        {
            get { return "202202231938056_46"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
